services:
  redis:
    image: redis:7-alpine
    container_name: anomaly-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: anomaly-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: anomaly-backend
    ports:
      - "8000:8000"
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_started

  ai_engine:
    build:
      context: .
      dockerfile: ai_engine/Dockerfile
    container_name: anomaly-ai-engine
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started

  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile
    container_name: anomaly-simulator
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
    depends_on:
      mosquitto:
        condition: service_started
      backend:
        condition: service_started
